default: &default
  adapter: 'mysql2'
  encoding: utf8
  pool: 5

development: &development
  <<: *default
  host: <%= ENV['TINYSIS_HOST'] %>
  database: <%= ENV['TINYSIS_DATABASE'] %>
  username: <%= ENV['TINYSIS_USER'] %>
  password: <%= ENV['TINYSIS_PASSWORD'] %>

test:
  <<: *development
  database: 'tinysis_test'

production:
  <<: *development
