development:
  secret_key_base: keystring-from-rake-secret
  auth0_api_audience: https://my.own.domain.com

  auth0_management:
    domain: auth0_assigned_domain.com
    client_id: clientId
    client_secret: clientSecret
    roles:
      - name: administrator
        id: rol_xxyyzz
      - name: staff
        id: rol_aabbcc
      - name: readonly
        id: rol_qqrrss

test:
  secret_key_base: keystring-from-rake-secret
  auth0_api_audience: https://my.own.domain.com
