development:
  secret_key_base: keystring-from-rake-secret
  auth0_api_audience: https://my.own.domain.com--from custom API "API audience"
  auth0_issuer: https://auth0_assigned_domain.com--from single-page application config "domain"

  auth0_management:
    domain: https://auth0_assigned_domain.com
    audience: https://auth0_issuer_domain/api/v2/
    client_id: clientId
    client_secret: clientSecret
    roles:
      - name: administrator
        id: rol_xxyyzz
      - name: staff
        id: rol_aabbcc
      - name: readonly
        id: rol_qqrrss

test:
  secret_key_base: keystring-from-rake-secret
  auth0_api_audience: https://my.own.domain.com
